//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Health.Model.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHospitalRegister
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblHospitalRegister()
        {
            this.tblHospitalDetails = new HashSet<tblHospitalDetail>();
            this.tblReviews = new HashSet<tblReview>();
            this.tblUsageDetails = new HashSet<tblUsageDetail>();
        }
    
        public int HospitalID { get; set; }
        public string HospitalName { get; set; }
        public string Description { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public decimal PinCode { get; set; }
        public decimal Phone { get; set; }
        public decimal Mobile { get; set; }
        public string Email { get; set; }
        public System.DateTime Date { get; set; }
        public bool Approval { get; set; }
        public string Id { get; set; }
        public string Password { get; set; }
        public Nullable<decimal> latitude { get; set; }
        public Nullable<decimal> longitude { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHospitalDetail> tblHospitalDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblReview> tblReviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUsageDetail> tblUsageDetails { get; set; }
    }
}
