//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Health.Model.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReview
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int HospitalID { get; set; }
        public string Review { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual tblHospitalRegister tblHospitalRegister { get; set; }
        public virtual tblUserRegister tblUserRegister { get; set; }
    }
}
